kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  app.conf: |
    events {
    }
    http {
      server {
          listen 80;
          server_name localhost;
          # root   /usr/share/nginx/html;
          # $document_rootの値となる
          #root /code;
          root /var/www/public;
          # index  index.html index.htm;
          index index.php index.html;

          access_log /var/log/nginx/access.log;
          error_log  /var/log/nginx/error.log;

          location / {
            try_files $uri $uri/ /index.php$is_args$args;
          }
          # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
          #
          location ~ \.php$ {
            # root           html;
            # root           /var/www/api-gateway/public;
            # docker-composeでホストが自動でリンク（設定）されるためサービス名が指定可能 -> php
            fastcgi_pass   127.0.0.1:9000;
            # fastcgi_pass   docker://5d8532a4122f6cd5e94318879f9beb90d0304fffee2ca43a38418d86083cb915:9000;
            # fastcgi_pass   sandar1234/its-dx-mgt-backend:9000;
            fastcgi_index  index.php;
            # FastCGIに渡すパラメータを修正
            # fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
          }
        }
    }
