name: Docker ECR and Kubernetes Deployment

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}

    - name: Build Docker image
      env:
        IMAGE_TAG: latest
      run: |
        DOCKER_TAG=$(echo "${GITHUB_REF}" | cut -d'/' -f 3)
        docker build -t gic-dx-its-mgt-api:$IMAGE_TAG .
        docker tag gic-dx-its-mgt-api:$IMAGE_TAG ${{ vars.ECR_REPOSITORY }}api:${DOCKER_TAG}
        docker tag gic-dx-its-mgt-api:$IMAGE_TAG ${{ vars.ECR_REPOSITORY }}api:$IMAGE_TAG

        docker build -t gic-dx-its-mgt-cjapan:$IMAGE_TAG .
        docker tag gic-dx-its-mgt-cjapan:$IMAGE_TAG ${{ vars.ECR_REPOSITORY }}cjapan:${DOCKER_TAG}
        docker tag gic-dx-its-mgt-cjapan:$IMAGE_TAG ${{ vars.ECR_REPOSITORY }}cjapan:$IMAGE_TAG

        docker build -t gic-dx-its-mgt-employees:$IMAGE_TAG .
        docker tag gic-dx-its-mgt-employees:$IMAGE_TAG ${{ vars.ECR_REPOSITORY }}employees:${DOCKER_TAG}
        docker tag gic-dx-its-mgt-employees:$IMAGE_TAG ${{ vars.ECR_REPOSITORY }}employees:$IMAGE_TAG

        docker build -t gic-dx-its-mgt-ejapan:$IMAGE_TAG .
        docker tag gic-dx-its-mgt-ejapan:$IMAGE_TAG ${{ vars.ECR_REPOSITORY }}ejapan:${DOCKER_TAG}
        docker tag gic-dx-its-mgt-ejapan:$IMAGE_TAG ${{ vars.ECR_REPOSITORY }}ejapan:$IMAGE_TAG

    - name: Authenticate to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ vars.AWS_DEFAULT_REGION}} | docker login --username AWS --password-stdin ${{ vars.ECR_REGISTRY }}

    - name: Push Docker image to Amazon ECR
      run: |
        DOCKER_TAG=$(echo "${GITHUB_REF}" | cut -d'/' -f 3)
        docker push ${{ vars.ECR_REPOSITORY }}api:${DOCKER_TAG}
        docker push ${{ vars.ECR_REPOSITORY }}api:latest

        docker push ${{ vars.ECR_REPOSITORY }}cjapan:${DOCKER_TAG}
        docker push ${{ vars.ECR_REPOSITORY }}cjapan:latest

        docker push ${{ vars.ECR_REPOSITORY }}employees:${DOCKER_TAG}
        docker push ${{ vars.ECR_REPOSITORY }}employees:latest

        docker push ${{ vars.ECR_REPOSITORY }}ejapan:${DOCKER_TAG}
        docker push ${{ vars.ECR_REPOSITORY }}ejapan:latest